# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-02 03:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_initial', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('k_code', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LastImportedId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('id_numeric', models.IntegerField()),
                ('id_string', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('accounting_endpoint', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('secret', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('transfer_fee', models.DecimalField(decimal_places=2, default='0.00', max_digits=5)),
                ('available_currencies', models.ManyToManyField(to='app.Currency')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Location')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.CharField(choices=[('B', 'BUY'), ('S', 'SELL')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('override_fee_percent', models.DecimalField(decimal_places=2, default='0.00', max_digits=5)),
                ('override_fee_sum', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('kraken_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('provisional', models.BooleanField(default=True)),
                ('bulk_loaded', models.BooleanField(default=False)),
                ('currency_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_from', to='app.Currency')),
                ('currency_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_to', to='app.Currency')),
                ('resource_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_from', to='app.Resource')),
                ('resource_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_to', to='app.Resource')),
                ('trader', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Trader')),
            ],
            options={
                'ordering': ['-date'],
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='trader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Trader'),
        ),
        migrations.AddField(
            model_name='lastimportedid',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Platform'),
        ),
        migrations.AddField(
            model_name='balance',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Currency'),
        ),
        migrations.AddField(
            model_name='balance',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Resource'),
        ),
        migrations.AddField(
            model_name='balance',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Trader'),
        ),
    ]
