# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-02 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='currency',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='location',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='resource',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='trader',
            managers=[
            ],
        ),
    ]
